# Generated by Django 5.2.1 on 2025-06-16 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalite',
            name='paiement',
        ),
        migrations.AddField(
            model_name='penalite',
            name='montant_payé',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paiementpenalite',
            name='penalite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='payments.penalite'),
        ),
    ]
