# Generated by Django 5.2.1 on 2025-06-14 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_categories', to='stations.chargecategory')),
            ],
            options={
                'verbose_name': 'Catégorie de charge',
                'verbose_name_plural': 'Catégories de charge',
                'db_table': 'charge_categories',
            },
        ),
        migrations.CreateModel(
            name='StationCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('periode', models.CharField(choices=[('mois', 'Mois'), ('annee', 'Année'), ('semaine', 'Semaine'), ('jour', 'Jour'), ('unique', 'Ponctuel')], default='mois', max_length=20)),
                ('date_charge', models.DateField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='stations.chargecategory')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='authentication.agence')),
            ],
            options={
                'verbose_name': 'Charge de station',
                'verbose_name_plural': 'Charges de station',
                'db_table': 'station_charges',
            },
        ),
    ]
