# Generated by Django 5.2.1 on 2025-06-15 13:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentabilityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_analyse', models.CharField(max_length=255)),
                ('type_periode', models.CharField(choices=[('day', 'Jour'), ('week', 'Semaine'), ('month', 'Mois'), ('quarter', 'Trimestre'), ('year', 'Année'), ('custom', 'Période personnalisée')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('revenus_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('charges_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('benefice_net', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('marge_beneficiaire', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nombre_swaps', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='authentication.agence')),
            ],
            options={
                'verbose_name': 'Analyse de rentabilité',
                'verbose_name_plural': 'Analyses de rentabilité',
                'db_table': 'rentability_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_moto_user_association_id', models.BigIntegerField()),
                ('battery_in_id', models.BigIntegerField()),
                ('battery_out_id', models.BigIntegerField()),
                ('swap_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('swap_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('battery_out_soc', models.CharField(blank=True, max_length=255, null=True)),
                ('battery_in_soc', models.CharField(blank=True, max_length=255, null=True)),
                ('agent_user_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(db_column='id_agence', on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to='authentication.agence')),
            ],
            options={
                'verbose_name': 'Swap de batterie',
                'verbose_name_plural': 'Swaps de batterie',
                'db_table': 'swaps',
            },
        ),
    ]
